add header and catalog
NazariiSova/react-bikcraft pull request #1
Opened 2023-03-18 08:25 UTC by NazariiSova

2023-03-18 08:26 UTC, taras-zherebetskiy commented
Test

2023-03-19 10:01 UTC, taras-zherebetskiy requested changes
Very nice 👍

2023-03-19 10:01 UTC, taras-zherebetskyi commented on public/index.html
> +    rel="stylesheet">
Can you import fonts shorter?

2023-03-19 10:01 UTC, taras-zherebetskyi commented on src/components/Nav.js
> +            <div className={"container"} >
```suggestion
            <div className="container" >
```

2023-03-19 10:01 UTC, taras-zherebetskyi commented on src/components/Nav.js
> +            <div className={"container"} >
Use 'nav' tag for navigations
* as parent tag for links

2023-03-19 10:01 UTC, taras-zherebetskyi commented on src/components/Nav.js
> +                <div className="headlines-others-container">
It will be better
```suggestion
                <div className="headlines-container">
```

2023-03-19 10:01 UTC, taras-zherebetskyi commented on src/components/Nav.js
>  const Nav = () => {
Here you have Header component not a Navigation

2023-03-19 10:01 UTC, taras-zherebetskyi commented on src/components/Nav.js
>  const Nav = () => {
Change name for component & file

2023-03-19 10:01 UTC, taras-zherebetskyi commented on src/pages/Home/Home.page.js
> +                        <div className="catalog-card-description"><li className="orange-mark"></li>Magic Migth</div>
```suggestion
                        <div className="catalog-card-description">Magic Migth</div>
```

use pseudo-element for mark

2023-03-19 10:01 UTC, taras-zherebetskyi commented on src/pages/Home/homePage.scss
> +}
move mixins to other file & import here

2023-03-19 10:01 UTC, taras-zherebetskiy commented on src/pages/Home/homePage.scss
> +$silver-color: #595959;
create a variable file and move it there

2023-03-19 12:58 UTC, NazariiSova commented on src/pages/Home/homePage.scss
> +}
Will this mixin work with class in this scss file, if i move this mixin to another file ?

2023-03-19 13:00 UTC, taras-zherebetskiy commented on src/pages/Home/homePage.scss
> +}
Yes, sure
But you need to use that mixin u need to import

2023-03-19 13:09 UTC, NazariiSova commented on src/pages/Home/Home.page.js
> +                        <div className="catalog-card-description"><li className="orange-mark"></li>Magic Migth</div>
done

2023-03-21 11:47 UTC, taras-zherebetskiy requested changes

2023-03-21 11:47 UTC, taras-zherebetskiy commented on src/pages/Home/Home.page.js
> +                    <div className="header-post-title">bicicletas feitas sob medida<span className="orange-point">.</span></div>
```suggestion
                    <div className="header-post-title">bicicletas feitas sob medida</div>
```

add dot as pseudo-class

2023-03-21 11:47 UTC, taras-zherebetskiy commented on src/pages/Home/Home.page.js
> +                <div className="catalog-title">escohola a sua<span className="orange-point">.</span></div>
add dot as pseudo-class

2023-03-21 11:47 UTC, taras-zherebetskiy commented on src/pages/Home/Home.page.js
> +                    <div className="diferencial-text-subtitle">Você escolhe as suas cores e componentes<span className="orange-point">.</span></div>
add dot as pseudo-class

2023-03-21 11:47 UTC, taras-zherebetskiy commented on src/pages/Home/Home.page.js
> +                <div className="partners-title">Nossos parceiros<span className="orange-point">.</span></div>
add dot as pseudo-class

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/components/footer/footer.scss
> +@import "../../components/styles/mixins.scss";
Very cool👍

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/components/footer/footer.scss
> +      width: 1600px;
Do not set static width

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/components/footer/footer.scss
> +      margin-bottom: 32px;
Better use only one type of margine (top or bottom)
*for avoid margin collapse

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/components/footer/footer.scss
> +      letter-spacing: 0.015em;
```suggestion
      font-size: 18px;
      font-weight: 400;
      line-height: 32px;
      letter-spacing: 0.015em;
      text-align: left;
  
      font-family: Roboto;
      font-size: 18px;
      font-weight: 500;
      line-height: 32px;
      letter-spacing: 0.015em;
```

remove duplicated font style

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/components/footer/footer.scss
> +      right: 1150px;
Avoid things like that

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/components/headlines.scss
> +    width: 133.54299926757812px;
Don’t use double numbers in css

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/pages/Bicicletas/Bicicletas.page.js
> +                <div className="header-smal-text">ESCOLHA A MELHORA PARA VOCÊ</div>
```suggestion
                <div className="header-small-text">ESCOLHA A MELHORA PARA VOCÊ</div>
```

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/pages/Bicicletas/bicicletasPage.scss
> +  &-smal-text {
```suggestion
  &-small-text {
```

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/pages/Bicicletas/bicicletasPage.scss
> +    background-color: #121212;
use variable for color

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/pages/Bicicletas/bicicletasPage.scss
> +    letter-spacing: 0em;
u don’t need set letter-spacing: 0
0 used as default value

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/pages/Bicicletas/bicicletasPage.scss
> +    }
Nice 🔥

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/pages/Home/Home.page.js
> +                        <img className="catalog-card-img" src={bicicleta2} alt="" />
Do not set empty string to alt

2023-03-25 21:39 UTC, taras-zherebetskiy commented on src/pages/Home/Home.page.js
> +                        </div>
try to reuse that block for 'OURO'

2023-03-26 10:11 UTC, NazariiSova commented on src/components/footer/footer.scss
> +      letter-spacing: 0.015em;
done

2023-03-26 10:29 UTC, NazariiSova commented on src/components/footer/footer.scss
> +      right: 1150px;
ok, i will fix that.

2023-03-26 17:07 UTC, NazariiSova commented on src/pages/Bicicletas/Bicicletas.page.js
> +                <div className="header-smal-text">ESCOLHA A MELHORA PARA VOCÊ</div>
thanks

2023-03-27 08:44 UTC, NazariiSova commented on src/components/Nav.js
> +            <div className={"container"} >
it necessarily ? Why ?

2023-03-27 08:46 UTC, NazariiSova commented on src/components/Nav.js
> +                <div className="headlines-others-container">
done

2023-03-27 08:56 UTC, NazariiSova commented on public/index.html
> +    rel="stylesheet">
done

2023-03-27 08:56 UTC, NazariiSova commented on src/components/Nav.js
>  const Nav = () => {
done

2023-03-27 08:57 UTC, NazariiSova commented on src/pages/Home/Home.page.js
> +                    <div className="header-post-title">bicicletas feitas sob medida<span className="orange-point">.</span></div>
done

2023-03-27 18:15 UTC, taras-zherebetskyi commented on src/components/footer/Footer.js
> +                        <li>contato@bikcraft.com</li>
TODO: make number & mail as link

2023-03-27 18:15 UTC, taras-zherebetskyi commented on src/components/header/Header.js
> +import "./headlines.scss"
Change name
```suggestion
import "./Header.scss"
```

2023-03-27 18:15 UTC, taras-zherebetskyi commented on src/components/header/headlines.scss
> +  margin-left: auto;
Better to use like this
```suggestion
  margin: 0 auto;
```

2023-03-27 18:15 UTC, taras-zherebetskyi commented on src/components/styles/variables.scss
> +$white-color: #ffffff;
```suggestion
$black-color: #000;
$white-color: #fff;
```

2023-03-27 18:15 UTC, taras-zherebetskiy commented on src/components/footer/footer.scss
> +    }
the first of all write styles for class then u can write other
```suggestion
margin-left: 300px;
      color: $light-gray-color;
      font-family: Roboto;
      font-size: 18px;
      font-weight: 500;
      line-height: 32px;
      letter-spacing: 0.015em;
      text-align: left;
      
      li {
        list-style-type: none;
        margin-left: -40px;
      }
    }
```

2023-03-29 07:24 UTC, taras-zherebetskiy commented on src/components/support-card/support-card.scss
> +      font-family: "Poppins";
try to use modificator 

Do not copy styles

2023-03-29 07:25 UTC, taras-zherebetskiy approved these changes

2023-03-29 09:23 UTC, merged