Page bicycles
NazariiSova/react-bikcraft pull request #2
Opened 2023-03-29 09:36 UTC by NazariiSova

2023-03-29 10:01 UTC, taras-zherebetskiy requested changes
Very nice 🔥

2023-03-29 10:01 UTC, taras-zherebetskyi commented on src/components/Bicicletas-catalog/BicicletasCatalog.jsx
> +        equipada com os melhores acessórios, o que garante maior velocidade.{" "}
Change description for different components

2023-03-29 10:01 UTC, taras-zherebetskyi commented on src/components/Bicicletas-catalog/BicicletasCatalog.jsx
> +    <div className={`bike-container${Background}`}>
```suggestion
  let Background = isDarkBackground ? "dark" : "light";
  return (
    <div className={`bike-container-${Background}`}>
```

2023-03-29 10:01 UTC, taras-zherebetskyi commented on src/components/Bicicletas-catalog/BicicletasCatalog.jsx
> +    <div className={`bike-container${Background}`}>
```suggestion
  let Background = isDarkBackground ? "-dark" : "-light";
  return (
    <div className={`bike-container bike-container--${Background}`}>
```

2023-03-29 10:01 UTC, taras-zherebetskyi commented on src/pages/Bicicletas/Bicicletas.page.jsx
> +        <BicicletasCatalog isDarkBackground={false} img={bicicleta3} price={"R$ 3.999"} title={"Mebula Cosmic"}/>
Make array and map it

2023-03-29 10:01 UTC, taras-zherebetskiy commented on src/pages/Bicicletas/bicicletasPage.scss
> +align-items: end;
```suggestion
align-items: flex-end;
```

2023-03-31 10:47 UTC, NazariiSova commented on src/components/Bicicletas-catalog/BicicletasCatalog.jsx
> +    <div className={`bike-container${Background}`}>
done

2023-03-31 10:49 UTC, NazariiSova commented on src/components/Bicicletas-catalog/BicicletasCatalog.jsx
> +    <div className={`bike-container${Background}`}>
done

2023-03-31 10:50 UTC, NazariiSova commented on src/pages/Bicicletas/bicicletasPage.scss
> +align-items: end;
done

2023-03-31 10:52 UTC, NazariiSova commented on src/components/Bicicletas-catalog/BicicletasCatalog.jsx
> +        equipada com os melhores acessórios, o que garante maior velocidade.{" "}
done

2023-03-31 13:10 UTC, NazariiSova commented on src/pages/Bicicletas/Bicicletas.page.jsx
> +        <BicicletasCatalog isDarkBackground={false} img={bicicleta3} price={"R$ 3.999"} title={"Mebula Cosmic"}/>
done

2023-04-01 19:54 UTC, taras-zherebetskiy approved these changes
So nice👍 
Fix comment & merge

2023-04-01 19:54 UTC, taras-zherebetskiy commented on src/components/Bicicletas-catalog/BicicletasCatalog.jsx
> +        {`A ${title}é a melhor Bikcraft já criada pela nossa equipe. Ela vem
```suggestion
        {`A ${title} é a melhor Bikcraft já criada pela nossa equipe. Ela vem
```

U need space here

2023-04-01 19:54 UTC, taras-zherebetskiy commented on src/pages/Home/Home.page.jsx
> +          <button className="header-post-button" > <Link className="header-post-button-link"to="/bicicletas">Selecione a sua</Link></button>
Use only link here

2023-04-04 09:37 UTC, NazariiSova commented on src/components/Bicicletas-catalog/BicicletasCatalog.jsx
> +        {`A ${title}é a melhor Bikcraft já criada pela nossa equipe. Ela vem
done

2023-04-04 09:42 UTC, NazariiSova commented on src/pages/Home/Home.page.jsx
> +          <button className="header-post-button" > <Link className="header-post-button-link"to="/bicicletas">Selecione a sua</Link></button>
done

2023-04-05 15:41 UTC, merged